### PR TITLE
crypto: ecdsa: fixup boot hang (fedora38-hardware).

### PR DESCRIPTION
**Pull request by twilfredo**
Finally trying this on hardware! When testing on Fedora38 (x86-HW), I ran into a hang during the boot process. Which seemed to be caused by a NULL de-reference of the encoding of the signature `req->enc`.

This patch adds a NULL check, that now allows the boot to proceed but I suppose it fails the ecdsa_verify. Perhaps there's  needs to be a followup to this to fix that?.

Also switch to `strncmp()` to be 'safer'.

Squish into commit: 09d3a2c

### CODE REVIEW

**Comment by l1k** [comment]
Did you get a stacktrace when the kernel oopsed or just a hang without screen output or logs?

If you did *not* get a stacktrace, could you add a `dump_stack();` in the if-clause to see where the invocation without encoding is coming from?

Thanks!

**Comment by twilfredo** [comment]
> Did you get a stacktrace when the kernel oopsed or just a hang without screen output or logs?
> 
It was basically a hang during the boot process.
> If you did _not_ get a stacktrace, could you add a `dump_stack();` in the if-clause to see where the invocation without encoding is coming from?
> 
Sure, this is the result:
```
[    1.713695] DBG_X: Dump Stack()
[    1.713696] CPU: 1 PID: 262 Comm: cryptomgr_test Not tainted 6.6.0-rc1-spdm+ #18
[    1.713698] Hardware name: Micro-Star International Co., Ltd. MS-7D17/MAG B560M MORTAR WIFI (MS-7D17), BIOS 1.B0 11/25/2022
[    1.713699] Call Trace:
[    1.713699]  <TASK>
[    1.713700]  dump_stack_lvl+0x47/0x60
[    1.713705]  ecdsa_verify+0x3a5/0x3f0
[    1.713709]  test_akcipher_one+0x588/0xbc0
[    1.713712]  alg_test_akcipher+0x60/0xd0
[    1.713713]  alg_test+0x199/0x630 
[    1.713714]  ? sched_clock_cpu+0xf/0x190 
[    1.713717]  ? __smp_call_single_queue+0xad/0x120
[    1.713719]  ? ttwu_queue_wakelist+0xef/0x110
[    1.713721]  ? __pfx_cryptomgr_test+0x10/0x10
[    1.713722]  cryptomgr_test+0x24/0x40
[    1.713723]  kthread+0xe5/0x120
[    1.713726]  ? __pfx_kthread+0x10/0x10
[    1.713727]  ret_from_fork+0x31/0x50
[    1.713730]  ? __pfx_kthread+0x10/0x10
[    1.713731]  ret_from_fork_asm+0x1b/0x30
[    1.713735]  </TASK>
[    1.713735] DBG_X: Dump Stack() END
[    1.713735] alg: akcipher: verify test failed. err -22
[    1.713737] alg: akcipher: test 1 failed for ecdsa-nist-p384-generic, err=-22
[    1.713738] alg: self-tests for ecdsa-nist-p384 using ecdsa-nist-p384-generic failed (rc=-22)
[    1.713739] ------------[ cut here ]------------
[    1.713739] alg: self-tests for ecdsa-nist-p384 using ecdsa-nist-p384-generic failed (rc=-22)
[    1.713746] WARNING: CPU: 1 PID: 262 at crypto/testmgr.c:5938 alg_test+0x516/0x630
[    1.713748] Modules linked in:
[    1.713749] CPU: 1 PID: 262 Comm: cryptomgr_test Not tainted 6.6.0-rc1-spdm+ #18
```
It looks like `test_akcipher_one()` in the call to `akcipher_request_set_crypt()`, NULL is passed in as the last argument. Dug around with a few more prints, and it seems `vecs->enc` is `NULL` and this call is also triggered `akcipher_request_set_crypt(req, src_tab, &dst, m_size, out_len_max, NULL);` . So eventually in the subsequent calls to `ecdsa_verify()` is called, it sees the `NULL` in `req->enc`.

> Thanks!

**Comment by l1k** [comment]
I neglected to update the ECDSA test vectors in `crypto/testmgr.h` to indicate they're x962 encoded. Thanks for reporting that, it spared me the embarrassment of submitting a broken patch to the mailing list. /o\

I've amended the test vectors now and that should fix the issue. I've added a debug patch (<a href="https://github.com/l1k/linux/commit/1d91f854b520e12820c71a6ae5c1f39f520edb11">crypto: ecdsa - Assume x962 encoding by default</a>) which emits a WARN splat if ecdsa verification is attempted without specifying the signature encoding. In theory you should never see the WARN splat. Just so that you don't experience another boot hang in case I've missed a code path where no encoding is specified.

About `strncmp` versus `strcmp`: Looking at the existing code in the crypto subsystem, everything seems to be using the `if (strcmp(...) == 0)` pattern and `strncmp` is only used when a prefix comparison is needed. I suspect that's a deliberate choice by the maintainer and trying to submit something which deviates from the existing style risks rejection. So I'd rather keep the `strcmp` for now.

Thanks again!

**Comment by twilfredo** [comment]
Awesome! thanks for the update!

**Comment by twilfredo** [comment]
closing this, issue is addressed.

**Pull request closed without merging**
